/** \file
 *  This C++ header file was generated by $ANTLR version 3.5
 *
 *     -  From the grammar source file : Prolog.g
 *     -                            On : 2013-10-11 03:11:32
 *     -                for the parser : PrologParserParser
 *
 * Editing it, at least manually, is not wise.
 *
 * C++ language generator and runtime by Gokulakannan Somasundaram ( heavy lifting from C Run-time by Jim Idle )
 *
 *
 * The parser 
PrologParser

has the callable functions (rules) shown below,
 * which will invoke the code for the associated rule in the source grammar
 * assuming that the input stream is pointing to a token/text stream that could begin
 * this rule.
 *
 * For instance if you call the first (topmost) rule in a parser grammar, you will
 * get the results of a full parse, but calling a rule half way through the grammar will
 * allow you to pass part of a full token stream to the parser, such as for syntax checking
 * in editors and so on.
 *
 */
// [The "BSD license"]
// Copyright (c) 2005-2009 Gokulakannan Somasundaram. 
//
// All rights reserved.
//
// Redistribution and use in source and binary forms, with or without
// modification, are permitted provided that the following conditions
// are met:
// 1. Redistributions of source code must retain the above copyright
//    notice, this list of conditions and the following disclaimer.
// 2. Redistributions in binary form must reproduce the above copyright
//    notice, this list of conditions and the following disclaimer in the
//    documentation and/or other materials provided with the distribution.
// 3. The name of the author may not be used to endorse or promote products
//    derived from this software without specific prior written permission.
//
// THIS SOFTWARE IS PROVIDED BY THE AUTHOR ``AS IS'' AND ANY EXPRESS OR
// IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED WARRANTIES
// OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE DISCLAIMED.
// IN NO EVENT SHALL THE AUTHOR BE LIABLE FOR ANY DIRECT, INDIRECT,
// INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT
// NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE,
// DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY
// THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT
// (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF
// THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.

#ifndef	_PrologParser_H
#define _PrologParser_H
/* =============================================================================
 * Standard antlr3 C++ runtime definitions
 */
#include    <antlr3.hpp>

/* End of standard antlr 3 runtime definitions
 * =============================================================================
 */


   #include "PrologLexer.hpp"




#ifdef	WIN32
// Disable: Unreferenced parameter,							- Rules with parameters that are not used
//          constant conditional,							- ANTLR realizes that a prediction is always true (synpred usually)
//          initialized but unused variable					- tree rewrite variables declared but not needed
//          Unreferenced local variable						- lexer rule declares but does not always use _type
//          potentially unitialized variable used			- retval always returned from a rule
//			unreferenced local function has been removed	- susually getTokenNames or freeScope, they can go without warnigns
//
// These are only really displayed at warning level /W4 but that is the code ideal I am aiming at
// and the codegen must generate some of these warnings by necessity, apart from 4100, which is
// usually generated when a parser rule is given a parameter that it does not use. Mostly though
// this is a matter of orthogonality hence I disable that one.
//
#pragma warning( disable : 4100 )
#pragma warning( disable : 4101 )
#pragma warning( disable : 4127 )
#pragma warning( disable : 4189 )
#pragma warning( disable : 4505 )
#pragma warning( disable : 4701 )
#endif

/* ========================
 * BACKTRACKING IS ENABLED
 * ========================
 */

	namespace 	User  {


typedef PrologParserTraits PrologParserImplTraits;

 struct synpred1_Prolog {}; 
 struct synpred2_Prolog {}; 
 struct synpred3_Prolog {}; 

class PrologParserTokens
{
public:
	/** Symbolic definitions of all the tokens that the 
parser
 will work with.
	 * \{
	 *
	 * Antlr will define EOF, but we can't use that as it it is too common in
	 * in C header files and that would be confusing. There is no way to filter this out at the moment
	 * so we just undef it here for now. That isn't the value we get back from C recognizers
	 * anyway. We are looking for ANTLR_TOKEN_EOF.
	 */
	enum Tokens 
	{
		EOF_TOKEN = PrologParserImplTraits::CommonTokenType::TOKEN_EOF
		, T__14 = 14 
		, T__15 = 15 
		, T__16 = 16 
		, T__17 = 17 
		, T__18 = 18 
		, ATOM = 4 
		, DIGIT = 5 
		, LOWERCASE = 6 
		, NUMBER = 7 
		, PRIME = 8 
		, SPECIAL = 9 
		, UNDERSCORE = 10 
		, UPPERCASE = 11 
		, VARIABLE = 12 
		, WS = 13 
	};

};

/** Context tracking structure for 
PrologParser

 */
class PrologParser : public 
PrologParserImplTraits::BaseParserType
, public PrologParserTokens
{
public:
	typedef PrologParserImplTraits ImplTraits;
	typedef PrologParser ComponentType;
	typedef ComponentType::StreamType StreamType;
	typedef 
PrologParserImplTraits::BaseParserType
 BaseType;
	typedef ImplTraits::RecognizerSharedStateType<StreamType> RecognizerSharedStateType;
	typedef StreamType InputType;
	static const bool IsFiltered = false;

	/* ruleAttributeScopeDecl(scope)
	 */
	/* makeScopeSet()
	 */
	 /** Definition of the rule scope variable tracking
	 *  structure. An instance of this structure is created by calling
	 *  PrologParser_rulePush().
	 */
	struct  ruleScope
	{
	    /* =============================================================================
	     * Programmer defined variables...
	     */
	    int NumAtoms;

	    /* End of programmer defined variables
	     * =============================================================================
	     */
	};



private:	
    /* ruleAttributeScopeDef(scope)
     */
    StackType< ruleScope >  m_rule_stack;



public:
    PrologParser(InputType* instream);
    PrologParser(InputType* instream, RecognizerSharedStateType* state);

    void init(InputType* instream  );

     
     void
     program (); 
     
     void
     comp_term (); 
     
     void
     term (); 
     
     void
     functor (); 
     
     void
     fact (); 
     
     void
     rule (); 
     
     void
     query (); 



      
     bool
     msynpred( antlr3::ClassForwarder< synpred1_Prolog > );
        void msynpred1_Prolog_fragment ();
      
     bool
     msynpred( antlr3::ClassForwarder< synpred2_Prolog > );
        void msynpred2_Prolog_fragment ();
      
     bool
     msynpred( antlr3::ClassForwarder< synpred3_Prolog > );
        void msynpred3_Prolog_fragment ();
    // Delegated rules

    const char *    getGrammarFileName();
    void            reset();
    ~PrologParser();

};

// Function protoypes for the constructor functions that external translation units
// such as delegators and delegates may wish to call.
//

/* End of token definitions for PrologParser
 * =============================================================================
 */
/** } */

	}


#endif

/* END - Note:Keep extra line feed to satisfy UNIX systems */
