/** \file
 *  This C++ source file was generated by $ANTLR version 3.5
 *
 *     -  From the grammar source file : Prolog.g
 *     -                            On : 2013-09-28 12:55:52
 *     -                for the parser : PrologParserParser
 *
 * Editing it, at least manually, is not wise.
 *
 * C++ language generator and runtime by Gokulakannan Somasundaram ( heavy lifting from C Run-time by Jim Idle )
 *
 *
*/
// [The "BSD license"]
// Copyright (c) 2005-2009 Gokulakannan Somasundaram, ElectronDB
//
// All rights reserved.
//
// Redistribution and use in source and binary forms, with or without
// modification, are permitted provided that the following conditions
// are met:
// 1. Redistributions of source code must retain the above copyright
//    notice, this list of conditions and the following disclaimer.
// 2. Redistributions in binary form must reproduce the above copyright
//    notice, this list of conditions and the following disclaimer in the
//    documentation and/or other materials provided with the distribution.
// 3. The name of the author may not be used to endorse or promote products
//    derived from this software without specific prior written permission.
//
// THIS SOFTWARE IS PROVIDED BY THE AUTHOR ``AS IS'' AND ANY EXPRESS OR
// IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED WARRANTIES
// OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE DISCLAIMED.
// IN NO EVENT SHALL THE AUTHOR BE LIABLE FOR ANY DIRECT, INDIRECT,
// INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT
// NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE,
// DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY
// THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT
// (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF
// THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.

/* -----------------------------------------
 * Include the ANTLR3 generated header file.
 */
#include    "PrologParser.hpp"
/* ----------------------------------------- */


/* ============================================================================= */

/* =============================================================================
 * Start of recognizer
 */

	namespace 	User  {

using namespace antlr3;
/** \brief Table of all token names in symbolic order, mainly used for
 *         error reporting.
 */
ANTLR_UINT8*   PrologParserTokenNames[15+4]
     = {
        (ANTLR_UINT8*) "<invalid>",       /* String to print to indicate an invalid token */
        (ANTLR_UINT8*) "<EOR>",
        (ANTLR_UINT8*) "<DOWN>",
        (ANTLR_UINT8*) "<UP>",
        (ANTLR_UINT8*) "ATOM",
        (ANTLR_UINT8*) "DIGIT",
        (ANTLR_UINT8*) "LOWERCASE",
        (ANTLR_UINT8*) "NUMBER",
        (ANTLR_UINT8*) "PRIME",
        (ANTLR_UINT8*) "SPECIAL",
        (ANTLR_UINT8*) "UNDERSCORE",
        (ANTLR_UINT8*) "UPPERCASE",
        (ANTLR_UINT8*) "VARIABLE",
        (ANTLR_UINT8*) "WS",
        (ANTLR_UINT8*) "'('",
        (ANTLR_UINT8*) "')'",
        (ANTLR_UINT8*) "','",
        (ANTLR_UINT8*) "'.'",
        (ANTLR_UINT8*) "':-'"
       };


/** \brief Name of the grammar file that generated this code
 */
static const char fileName[] = "Prolog.g";

/** \brief Return the name of the grammar file that generated this code.
 */
const char* PrologParser::getGrammarFileName()
{
	return fileName;
}
/** \brief Create a new PrologParser parser and return a context for it.
 *
 * \param[in] instream Pointer to an input stream interface.
 *
 * \return Pointer to new parser context upon success.
 */
PrologParser::PrologParser( StreamType* instream)
    :ImplTraits::BaseParserType(ANTLR_SIZE_HINT, instream, NULL)

{
	// See if we can create a new parser with the standard constructor
	//
	this->init(instream);
}

/** \brief Create a new PrologParser parser and return a context for it.
 *
 * \param[in] instream Pointer to an input stream interface.
 *
 * \return Pointer to new parser context upon success.
 */
PrologParser::PrologParser( StreamType* instream, RecognizerSharedStateType* state)
    :ImplTraits::BaseParserType(ANTLR_SIZE_HINT, instream, state)

{
	this->init(instream );
}

void PrologParser::init(StreamType* instream)
{
	/* Install the token table
	*/
	this->get_psrstate()->set_tokenNames( PrologParserTokenNames );


}

void
PrologParser::reset()
{
    this->get_rec()->reset();
}

/** Free the parser resources
 */
PrologParser::~PrologParser()
 {
}

/** Return token names used by this 
parser

 *
 * The returned pointer is used as an index into the token names table (using the token
 * number as the index).
 *
 * \return Pointer to first char * in the table.
 */
static ANTLR_UINT8**	getTokenNames()
{
        return PrologParserTokenNames;
}


/* Declare the bitsets
 */
/** Bitset defining follow set for error recovery in rule state: PrologParser  */
static	ANTLR_BITWORD FOLLOW_fact_in_program86_bits[]	= { ANTLR_UINT64_LIT(0x0000000000000012) };
static  PrologParserImplTraits::BitsetListType FOLLOW_fact_in_program86( FOLLOW_fact_in_program86_bits, 1 );
/** Bitset defining follow set for error recovery in rule state: PrologParser  */
static	ANTLR_BITWORD FOLLOW_rule_in_program90_bits[]	= { ANTLR_UINT64_LIT(0x0000000000000012) };
static  PrologParserImplTraits::BitsetListType FOLLOW_rule_in_program90( FOLLOW_rule_in_program90_bits, 1 );
/** Bitset defining follow set for error recovery in rule state: PrologParser  */
static	ANTLR_BITWORD FOLLOW_query_in_program94_bits[]	= { ANTLR_UINT64_LIT(0x0000000000000012) };
static  PrologParserImplTraits::BitsetListType FOLLOW_query_in_program94( FOLLOW_query_in_program94_bits, 1 );
/** Bitset defining follow set for error recovery in rule state: PrologParser  */
static	ANTLR_BITWORD FOLLOW_functor_in_comp_term115_bits[]	= { ANTLR_UINT64_LIT(0x0000000000004000) };
static  PrologParserImplTraits::BitsetListType FOLLOW_functor_in_comp_term115( FOLLOW_functor_in_comp_term115_bits, 1 );
/** Bitset defining follow set for error recovery in rule state: PrologParser  */
static	ANTLR_BITWORD FOLLOW_14_in_comp_term117_bits[]	= { ANTLR_UINT64_LIT(0x0000000000001090) };
static  PrologParserImplTraits::BitsetListType FOLLOW_14_in_comp_term117( FOLLOW_14_in_comp_term117_bits, 1 );
/** Bitset defining follow set for error recovery in rule state: PrologParser  */
static	ANTLR_BITWORD FOLLOW_term_in_comp_term119_bits[]	= { ANTLR_UINT64_LIT(0x0000000000018000) };
static  PrologParserImplTraits::BitsetListType FOLLOW_term_in_comp_term119( FOLLOW_term_in_comp_term119_bits, 1 );
/** Bitset defining follow set for error recovery in rule state: PrologParser  */
static	ANTLR_BITWORD FOLLOW_16_in_comp_term122_bits[]	= { ANTLR_UINT64_LIT(0x0000000000001090) };
static  PrologParserImplTraits::BitsetListType FOLLOW_16_in_comp_term122( FOLLOW_16_in_comp_term122_bits, 1 );
/** Bitset defining follow set for error recovery in rule state: PrologParser  */
static	ANTLR_BITWORD FOLLOW_term_in_comp_term124_bits[]	= { ANTLR_UINT64_LIT(0x0000000000018000) };
static  PrologParserImplTraits::BitsetListType FOLLOW_term_in_comp_term124( FOLLOW_term_in_comp_term124_bits, 1 );
/** Bitset defining follow set for error recovery in rule state: PrologParser  */
static	ANTLR_BITWORD FOLLOW_15_in_comp_term128_bits[]	= { ANTLR_UINT64_LIT(0x0000000000000002) };
static  PrologParserImplTraits::BitsetListType FOLLOW_15_in_comp_term128( FOLLOW_15_in_comp_term128_bits, 1 );
/** Bitset defining follow set for error recovery in rule state: PrologParser  */
static	ANTLR_BITWORD FOLLOW_NUMBER_in_term139_bits[]	= { ANTLR_UINT64_LIT(0x0000000000000002) };
static  PrologParserImplTraits::BitsetListType FOLLOW_NUMBER_in_term139( FOLLOW_NUMBER_in_term139_bits, 1 );
/** Bitset defining follow set for error recovery in rule state: PrologParser  */
static	ANTLR_BITWORD FOLLOW_VARIABLE_in_term151_bits[]	= { ANTLR_UINT64_LIT(0x0000000000000002) };
static  PrologParserImplTraits::BitsetListType FOLLOW_VARIABLE_in_term151( FOLLOW_VARIABLE_in_term151_bits, 1 );
/** Bitset defining follow set for error recovery in rule state: PrologParser  */
static	ANTLR_BITWORD FOLLOW_ATOM_in_term163_bits[]	= { ANTLR_UINT64_LIT(0x0000000000000002) };
static  PrologParserImplTraits::BitsetListType FOLLOW_ATOM_in_term163( FOLLOW_ATOM_in_term163_bits, 1 );
/** Bitset defining follow set for error recovery in rule state: PrologParser  */
static	ANTLR_BITWORD FOLLOW_comp_term_in_term175_bits[]	= { ANTLR_UINT64_LIT(0x0000000000000002) };
static  PrologParserImplTraits::BitsetListType FOLLOW_comp_term_in_term175( FOLLOW_comp_term_in_term175_bits, 1 );
/** Bitset defining follow set for error recovery in rule state: PrologParser  */
static	ANTLR_BITWORD FOLLOW_ATOM_in_functor192_bits[]	= { ANTLR_UINT64_LIT(0x0000000000000002) };
static  PrologParserImplTraits::BitsetListType FOLLOW_ATOM_in_functor192( FOLLOW_ATOM_in_functor192_bits, 1 );
/** Bitset defining follow set for error recovery in rule state: PrologParser  */
static	ANTLR_BITWORD FOLLOW_ATOM_in_fact205_bits[]	= { ANTLR_UINT64_LIT(0x0000000000020000) };
static  PrologParserImplTraits::BitsetListType FOLLOW_ATOM_in_fact205( FOLLOW_ATOM_in_fact205_bits, 1 );
/** Bitset defining follow set for error recovery in rule state: PrologParser  */
static	ANTLR_BITWORD FOLLOW_comp_term_in_fact209_bits[]	= { ANTLR_UINT64_LIT(0x0000000000020000) };
static  PrologParserImplTraits::BitsetListType FOLLOW_comp_term_in_fact209( FOLLOW_comp_term_in_fact209_bits, 1 );
/** Bitset defining follow set for error recovery in rule state: PrologParser  */
static	ANTLR_BITWORD FOLLOW_17_in_fact211_bits[]	= { ANTLR_UINT64_LIT(0x0000000000000002) };
static  PrologParserImplTraits::BitsetListType FOLLOW_17_in_fact211( FOLLOW_17_in_fact211_bits, 1 );
/** Bitset defining follow set for error recovery in rule state: PrologParser  */
static	ANTLR_BITWORD FOLLOW_ATOM_in_rule234_bits[]	= { ANTLR_UINT64_LIT(0x0000000000040000) };
static  PrologParserImplTraits::BitsetListType FOLLOW_ATOM_in_rule234( FOLLOW_ATOM_in_rule234_bits, 1 );
/** Bitset defining follow set for error recovery in rule state: PrologParser  */
static	ANTLR_BITWORD FOLLOW_comp_term_in_rule238_bits[]	= { ANTLR_UINT64_LIT(0x0000000000040000) };
static  PrologParserImplTraits::BitsetListType FOLLOW_comp_term_in_rule238( FOLLOW_comp_term_in_rule238_bits, 1 );
/** Bitset defining follow set for error recovery in rule state: PrologParser  */
static	ANTLR_BITWORD FOLLOW_18_in_rule241_bits[]	= { ANTLR_UINT64_LIT(0x0000000000000010) };
static  PrologParserImplTraits::BitsetListType FOLLOW_18_in_rule241( FOLLOW_18_in_rule241_bits, 1 );
/** Bitset defining follow set for error recovery in rule state: PrologParser  */
static	ANTLR_BITWORD FOLLOW_ATOM_in_rule244_bits[]	= { ANTLR_UINT64_LIT(0x0000000000030000) };
static  PrologParserImplTraits::BitsetListType FOLLOW_ATOM_in_rule244( FOLLOW_ATOM_in_rule244_bits, 1 );
/** Bitset defining follow set for error recovery in rule state: PrologParser  */
static	ANTLR_BITWORD FOLLOW_comp_term_in_rule248_bits[]	= { ANTLR_UINT64_LIT(0x0000000000030000) };
static  PrologParserImplTraits::BitsetListType FOLLOW_comp_term_in_rule248( FOLLOW_comp_term_in_rule248_bits, 1 );
/** Bitset defining follow set for error recovery in rule state: PrologParser  */
static	ANTLR_BITWORD FOLLOW_16_in_rule252_bits[]	= { ANTLR_UINT64_LIT(0x0000000000000010) };
static  PrologParserImplTraits::BitsetListType FOLLOW_16_in_rule252( FOLLOW_16_in_rule252_bits, 1 );
/** Bitset defining follow set for error recovery in rule state: PrologParser  */
static	ANTLR_BITWORD FOLLOW_ATOM_in_rule255_bits[]	= { ANTLR_UINT64_LIT(0x0000000000030000) };
static  PrologParserImplTraits::BitsetListType FOLLOW_ATOM_in_rule255( FOLLOW_ATOM_in_rule255_bits, 1 );
/** Bitset defining follow set for error recovery in rule state: PrologParser  */
static	ANTLR_BITWORD FOLLOW_comp_term_in_rule259_bits[]	= { ANTLR_UINT64_LIT(0x0000000000030000) };
static  PrologParserImplTraits::BitsetListType FOLLOW_comp_term_in_rule259( FOLLOW_comp_term_in_rule259_bits, 1 );
/** Bitset defining follow set for error recovery in rule state: PrologParser  */
static	ANTLR_BITWORD FOLLOW_17_in_rule264_bits[]	= { ANTLR_UINT64_LIT(0x0000000000000002) };
static  PrologParserImplTraits::BitsetListType FOLLOW_17_in_rule264( FOLLOW_17_in_rule264_bits, 1 );
/** Bitset defining follow set for error recovery in rule state: PrologParser  */
static	ANTLR_BITWORD FOLLOW_ATOM_in_query288_bits[]	= { ANTLR_UINT64_LIT(0x0000000000030000) };
static  PrologParserImplTraits::BitsetListType FOLLOW_ATOM_in_query288( FOLLOW_ATOM_in_query288_bits, 1 );
/** Bitset defining follow set for error recovery in rule state: PrologParser  */
static	ANTLR_BITWORD FOLLOW_comp_term_in_query292_bits[]	= { ANTLR_UINT64_LIT(0x0000000000030000) };
static  PrologParserImplTraits::BitsetListType FOLLOW_comp_term_in_query292( FOLLOW_comp_term_in_query292_bits, 1 );
/** Bitset defining follow set for error recovery in rule state: PrologParser  */
static	ANTLR_BITWORD FOLLOW_16_in_query296_bits[]	= { ANTLR_UINT64_LIT(0x0000000000000010) };
static  PrologParserImplTraits::BitsetListType FOLLOW_16_in_query296( FOLLOW_16_in_query296_bits, 1 );
/** Bitset defining follow set for error recovery in rule state: PrologParser  */
static	ANTLR_BITWORD FOLLOW_ATOM_in_query299_bits[]	= { ANTLR_UINT64_LIT(0x0000000000030000) };
static  PrologParserImplTraits::BitsetListType FOLLOW_ATOM_in_query299( FOLLOW_ATOM_in_query299_bits, 1 );
/** Bitset defining follow set for error recovery in rule state: PrologParser  */
static	ANTLR_BITWORD FOLLOW_comp_term_in_query303_bits[]	= { ANTLR_UINT64_LIT(0x0000000000030000) };
static  PrologParserImplTraits::BitsetListType FOLLOW_comp_term_in_query303( FOLLOW_comp_term_in_query303_bits, 1 );
/** Bitset defining follow set for error recovery in rule state: PrologParser  */
static	ANTLR_BITWORD FOLLOW_17_in_query308_bits[]	= { ANTLR_UINT64_LIT(0x0000000000000002) };
static  PrologParserImplTraits::BitsetListType FOLLOW_17_in_query308( FOLLOW_17_in_query308_bits, 1 );
/** Bitset defining follow set for error recovery in rule state: PrologParser  */
static	ANTLR_BITWORD FOLLOW_fact_in_synpred1_Prolog86_bits[]	= { ANTLR_UINT64_LIT(0x0000000000000002) };
static  PrologParserImplTraits::BitsetListType FOLLOW_fact_in_synpred1_Prolog86( FOLLOW_fact_in_synpred1_Prolog86_bits, 1 );
/** Bitset defining follow set for error recovery in rule state: PrologParser  */
static	ANTLR_BITWORD FOLLOW_rule_in_synpred2_Prolog90_bits[]	= { ANTLR_UINT64_LIT(0x0000000000000002) };
static  PrologParserImplTraits::BitsetListType FOLLOW_rule_in_synpred2_Prolog90( FOLLOW_rule_in_synpred2_Prolog90_bits, 1 );
/** Bitset defining follow set for error recovery in rule state: PrologParser  */
static	ANTLR_BITWORD FOLLOW_query_in_synpred3_Prolog94_bits[]	= { ANTLR_UINT64_LIT(0x0000000000000002) };
static  PrologParserImplTraits::BitsetListType FOLLOW_query_in_synpred3_Prolog94( FOLLOW_query_in_synpred3_Prolog94_bits, 1 );


/* ==============================================
 * Parsing rules
 */
/**
 * $ANTLR start program
 * Prolog.g:31:1: program : ( fact | rule | query )+ ;
 */
void
PrologParser::program()
{
        PrologParserImplTraits::RuleReturnValueType _antlr_rule_exit(this);
      

    /* Initialize rule variables
     */


 
    {
        // Prolog.g:31:9: ( ( fact | rule | query )+ )
        // Prolog.g:31:11: ( fact | rule | query )+
        {
            // Prolog.g:31:11: ( fact | rule | query )+
            {
                int cnt1=0;

                for (;;)
                {
                    int alt1=4;
            	switch ( this->LA(1) )
            	{
            	case ATOM:
            		{
            			{
            			   /* dfaLoopbackState(k,edges,eotPredictsAlt,description,stateNumber,semPredState)
            			    */
            			    int LA1_2 = this->LA(2);
            			    if ( (this->msynpred( antlr3::ClassForwarder<synpred1_Prolog>() )))
            			    {
            			        alt1=1;
            			    }
            			    else if ( (this->msynpred( antlr3::ClassForwarder<synpred2_Prolog>() )))
            			    {
            			        alt1=2;
            			    }
            			    else if ( (this->msynpred( antlr3::ClassForwarder<synpred3_Prolog>() )))
            			    {
            			        alt1=3;
            			    }

            			}
            		}
            	    break;

            	}

            	switch (alt1)
            	{
            	    case 1:
            	        // Prolog.g:31:12: fact
            	        {
            	            this->followPush(FOLLOW_fact_in_program86);
            	            fact();

            	            this->followPop();
            	            if  (this->hasException())
            	            {
            	                goto ruleprogramEx;
            	            }
            	            if (this->hasFailed())
            	            {
            	                return ;
            	            }


            	        }
            	        break;
            	    case 2:
            	        // Prolog.g:31:19: rule
            	        {
            	            this->followPush(FOLLOW_rule_in_program90);
            	            rule();

            	            this->followPop();
            	            if  (this->hasException())
            	            {
            	                goto ruleprogramEx;
            	            }
            	            if (this->hasFailed())
            	            {
            	                return ;
            	            }


            	        }
            	        break;
            	    case 3:
            	        // Prolog.g:31:26: query
            	        {
            	            this->followPush(FOLLOW_query_in_program94);
            	            query();

            	            this->followPop();
            	            if  (this->hasException())
            	            {
            	                goto ruleprogramEx;
            	            }
            	            if (this->hasFailed())
            	            {
            	                return ;
            	            }


            	        }
            	        break;

            	    default:

            		if ( cnt1 >= 1 )
            		{
            		    goto loop1;
            		}
            		if (this->get_backtracking()>0)
            		{
            		    this->set_failedflag( true );
            		    return ;
            		}

            		/* mismatchedSetEx()
            		 */
            		new ANTLR_Exception< PrologParserImplTraits, EARLY_EXIT_EXCEPTION, StreamType>( this->get_rec(), "" );


            		goto ruleprogramEx;
            	}
            	cnt1++;
                }
                loop1: ;	/* Jump to here if this rule does not match */
            }

        }

    }
    // This is where rules clean up and exit
    //
    goto ruleprogramEx; /* Prevent compiler warnings */
    ruleprogramEx: ;


    	if (this->hasException())
        {
            this->preporterror();
            this->precover();
        }
    return ;
}
/* $ANTLR end program */

/**
 * $ANTLR start comp_term
 * Prolog.g:34:1: comp_term : functor '(' term ( ',' term )* ')' ;
 */
void
PrologParser::comp_term()
{
        PrologParserImplTraits::RuleReturnValueType _antlr_rule_exit(this);
      

    /* Initialize rule variables
     */


 
    {
        // Prolog.g:34:13: ( functor '(' term ( ',' term )* ')' )
        // Prolog.g:34:15: functor '(' term ( ',' term )* ')'
        {
            this->followPush(FOLLOW_functor_in_comp_term115);
            functor();

            this->followPop();
            if  (this->hasException())
            {
                goto rulecomp_termEx;
            }
            if (this->hasFailed())
            {
                return ;
            }


             this->matchToken(14, &FOLLOW_14_in_comp_term117);
            if  (this->hasException())
            {
                goto rulecomp_termEx;
            }
            if (this->hasFailed())
            {
                return ;
            }


            this->followPush(FOLLOW_term_in_comp_term119);
            term();

            this->followPop();
            if  (this->hasException())
            {
                goto rulecomp_termEx;
            }
            if (this->hasFailed())
            {
                return ;
            }


            // Prolog.g:34:32: ( ',' term )*

            for (;;)
            {
                int alt2=2;
                switch ( this->LA(1) )
                {
                case 16:
                	{
                		alt2=1;
                	}
                    break;

                }

                switch (alt2)
                {
            	case 1:
            	    // Prolog.g:34:33: ',' term
            	    {
            	         this->matchToken(16, &FOLLOW_16_in_comp_term122);
            	        if  (this->hasException())
            	        {
            	            goto rulecomp_termEx;
            	        }
            	        if (this->hasFailed())
            	        {
            	            return ;
            	        }


            	        this->followPush(FOLLOW_term_in_comp_term124);
            	        term();

            	        this->followPop();
            	        if  (this->hasException())
            	        {
            	            goto rulecomp_termEx;
            	        }
            	        if (this->hasFailed())
            	        {
            	            return ;
            	        }


            	    }
            	    break;

            	default:
            	    goto loop2;	/* break out of the loop */
            	    break;
                }
            }
            loop2: ; /* Jump out to here if this rule does not match */


             this->matchToken(15, &FOLLOW_15_in_comp_term128);
            if  (this->hasException())
            {
                goto rulecomp_termEx;
            }
            if (this->hasFailed())
            {
                return ;
            }


        }

    }
    // This is where rules clean up and exit
    //
    goto rulecomp_termEx; /* Prevent compiler warnings */
    rulecomp_termEx: ;


    	if (this->hasException())
        {
            this->preporterror();
            this->precover();
        }
    return ;
}
/* $ANTLR end comp_term */

/**
 * $ANTLR start term
 * Prolog.g:36:1: term : ( NUMBER | VARIABLE | ATOM | comp_term );
 */
void
PrologParser::term()
{
        PrologParserImplTraits::RuleReturnValueType _antlr_rule_exit(this);
      

    /* Initialize rule variables
     */


 
    {
        {
            //  Prolog.g:36:9: ( NUMBER | VARIABLE | ATOM | comp_term )

            ANTLR_UINT32 alt3;

            alt3=4;

            switch ( this->LA(1) )
            {
            case NUMBER:
            	{
            		alt3=1;
            	}
                break;
            case VARIABLE:
            	{
            		alt3=2;
            	}
                break;
            case ATOM:
            	{
            		switch ( this->LA(2) )
            		{
            		case EOF:
            		case 15:
            		case 16:
            			{
            				alt3=3;
            			}
            		    break;
            		case 14:
            			{
            				alt3=4;
            			}
            		    break;

            		default:
            		    if (this->get_backtracking()>0)
            		    {
            		        this->set_failedflag( true );
            		        return ;
            		    }

            		    ExceptionBaseType* ex = new ANTLR_Exception< PrologParserImplTraits, NO_VIABLE_ALT_EXCEPTION, StreamType>( this->get_rec(), "" );
            		    ex->set_decisionNum( 3 );
            		    ex->set_state( 3 );


            		    goto ruletermEx;

            		}

            	}
                break;

            default:
                if (this->get_backtracking()>0)
                {
                    this->set_failedflag( true );
                    return ;
                }

                ExceptionBaseType* ex = new ANTLR_Exception< PrologParserImplTraits, NO_VIABLE_ALT_EXCEPTION, StreamType>( this->get_rec(), "" );
                ex->set_decisionNum( 3 );
                ex->set_state( 0 );


                goto ruletermEx;

            }

            switch (alt3)
            {
        	case 1:
        	    // Prolog.g:36:11: NUMBER
        	    {
        	         this->matchToken(NUMBER, &FOLLOW_NUMBER_in_term139);
        	        if  (this->hasException())
        	        {
        	            goto ruletermEx;
        	        }
        	        if (this->hasFailed())
        	        {
        	            return ;
        	        }


        	    }
        	    break;
        	case 2:
        	    // Prolog.g:37:11: VARIABLE
        	    {
        	         this->matchToken(VARIABLE, &FOLLOW_VARIABLE_in_term151);
        	        if  (this->hasException())
        	        {
        	            goto ruletermEx;
        	        }
        	        if (this->hasFailed())
        	        {
        	            return ;
        	        }


        	    }
        	    break;
        	case 3:
        	    // Prolog.g:38:11: ATOM
        	    {
        	         this->matchToken(ATOM, &FOLLOW_ATOM_in_term163);
        	        if  (this->hasException())
        	        {
        	            goto ruletermEx;
        	        }
        	        if (this->hasFailed())
        	        {
        	            return ;
        	        }


        	    }
        	    break;
        	case 4:
        	    // Prolog.g:39:11: comp_term
        	    {
        	        this->followPush(FOLLOW_comp_term_in_term175);
        	        comp_term();

        	        this->followPop();
        	        if  (this->hasException())
        	        {
        	            goto ruletermEx;
        	        }
        	        if (this->hasFailed())
        	        {
        	            return ;
        	        }


        	    }
        	    break;

            }
        }
    }
    // This is where rules clean up and exit
    //
    goto ruletermEx; /* Prevent compiler warnings */
    ruletermEx: ;


    	if (this->hasException())
        {
            this->preporterror();
            this->precover();
        }
    return ;
}
/* $ANTLR end term */

/**
 * $ANTLR start functor
 * Prolog.g:42:1: functor : ATOM ;
 */
void
PrologParser::functor()
{
        PrologParserImplTraits::RuleReturnValueType _antlr_rule_exit(this);
      

    /* Initialize rule variables
     */


 
    {
        // Prolog.g:42:9: ( ATOM )
        // Prolog.g:42:11: ATOM
        {
             this->matchToken(ATOM, &FOLLOW_ATOM_in_functor192);
            if  (this->hasException())
            {
                goto rulefunctorEx;
            }
            if (this->hasFailed())
            {
                return ;
            }


        }

    }
    // This is where rules clean up and exit
    //
    goto rulefunctorEx; /* Prevent compiler warnings */
    rulefunctorEx: ;


    	if (this->hasException())
        {
            this->preporterror();
            this->precover();
        }
    return ;
}
/* $ANTLR end functor */

/**
 * $ANTLR start fact
 * Prolog.g:45:1: fact : ( ATOM | comp_term ) '.' ;
 */
void
PrologParser::fact()
{
        PrologParserImplTraits::RuleReturnValueType _antlr_rule_exit(this);
      

    /* Initialize rule variables
     */


 
    {
        // Prolog.g:45:9: ( ( ATOM | comp_term ) '.' )
        // Prolog.g:45:11: ( ATOM | comp_term ) '.'
        {
            // Prolog.g:45:11: ( ATOM | comp_term )
            {
                int alt4=2;
                switch ( this->LA(1) )
                {
                case ATOM:
                	{
                		switch ( this->LA(2) )
                		{
                		case 17:
                			{
                				alt4=1;
                			}
                		    break;
                		case 14:
                			{
                				alt4=2;
                			}
                		    break;

                		default:
                		    if (this->get_backtracking()>0)
                		    {
                		        this->set_failedflag( true );
                		        return ;
                		    }

                		    ExceptionBaseType* ex = new ANTLR_Exception< PrologParserImplTraits, NO_VIABLE_ALT_EXCEPTION, StreamType>( this->get_rec(), "" );
                		    ex->set_decisionNum( 4 );
                		    ex->set_state( 1 );


                		    goto rulefactEx;

                		}

                	}
                    break;

                default:
                    if (this->get_backtracking()>0)
                    {
                        this->set_failedflag( true );
                        return ;
                    }

                    ExceptionBaseType* ex = new ANTLR_Exception< PrologParserImplTraits, NO_VIABLE_ALT_EXCEPTION, StreamType>( this->get_rec(), "" );
                    ex->set_decisionNum( 4 );
                    ex->set_state( 0 );


                    goto rulefactEx;

                }

                switch (alt4)
                {
            	case 1:
            	    // Prolog.g:45:12: ATOM
            	    {
            	         this->matchToken(ATOM, &FOLLOW_ATOM_in_fact205);
            	        if  (this->hasException())
            	        {
            	            goto rulefactEx;
            	        }
            	        if (this->hasFailed())
            	        {
            	            return ;
            	        }


            	    }
            	    break;
            	case 2:
            	    // Prolog.g:45:19: comp_term
            	    {
            	        this->followPush(FOLLOW_comp_term_in_fact209);
            	        comp_term();

            	        this->followPop();
            	        if  (this->hasException())
            	        {
            	            goto rulefactEx;
            	        }
            	        if (this->hasFailed())
            	        {
            	            return ;
            	        }


            	    }
            	    break;

                }
            }

             this->matchToken(17, &FOLLOW_17_in_fact211);
            if  (this->hasException())
            {
                goto rulefactEx;
            }
            if (this->hasFailed())
            {
                return ;
            }


            if ( this->get_backtracking()==0 )
            {
                std::cout << "matched a fact!" << std::endl;
            }


        }

    }
    // This is where rules clean up and exit
    //
    goto rulefactEx; /* Prevent compiler warnings */
    rulefactEx: ;


    	if (this->hasException())
        {
            this->preporterror();
            this->precover();
        }
    return ;
}
/* $ANTLR end fact */

/**
 * $ANTLR start rule
 * Prolog.g:48:1: rule : ( ATOM | comp_term ) ':-' ( ATOM | comp_term ) ( ',' ( ATOM | comp_term ) )* '.' ;
 */
void
PrologParser::rule()
{
        PrologParserImplTraits::RuleReturnValueType _antlr_rule_exit(this);
      

    /* Initialize rule variables
     */


 
    {
        // Prolog.g:48:9: ( ( ATOM | comp_term ) ':-' ( ATOM | comp_term ) ( ',' ( ATOM | comp_term ) )* '.' )
        // Prolog.g:48:11: ( ATOM | comp_term ) ':-' ( ATOM | comp_term ) ( ',' ( ATOM | comp_term ) )* '.'
        {
            // Prolog.g:48:11: ( ATOM | comp_term )
            {
                int alt5=2;
                switch ( this->LA(1) )
                {
                case ATOM:
                	{
                		switch ( this->LA(2) )
                		{
                		case 18:
                			{
                				alt5=1;
                			}
                		    break;
                		case 14:
                			{
                				alt5=2;
                			}
                		    break;

                		default:
                		    if (this->get_backtracking()>0)
                		    {
                		        this->set_failedflag( true );
                		        return ;
                		    }

                		    ExceptionBaseType* ex = new ANTLR_Exception< PrologParserImplTraits, NO_VIABLE_ALT_EXCEPTION, StreamType>( this->get_rec(), "" );
                		    ex->set_decisionNum( 5 );
                		    ex->set_state( 1 );


                		    goto ruleruleEx;

                		}

                	}
                    break;

                default:
                    if (this->get_backtracking()>0)
                    {
                        this->set_failedflag( true );
                        return ;
                    }

                    ExceptionBaseType* ex = new ANTLR_Exception< PrologParserImplTraits, NO_VIABLE_ALT_EXCEPTION, StreamType>( this->get_rec(), "" );
                    ex->set_decisionNum( 5 );
                    ex->set_state( 0 );


                    goto ruleruleEx;

                }

                switch (alt5)
                {
            	case 1:
            	    // Prolog.g:48:12: ATOM
            	    {
            	         this->matchToken(ATOM, &FOLLOW_ATOM_in_rule234);
            	        if  (this->hasException())
            	        {
            	            goto ruleruleEx;
            	        }
            	        if (this->hasFailed())
            	        {
            	            return ;
            	        }


            	    }
            	    break;
            	case 2:
            	    // Prolog.g:48:19: comp_term
            	    {
            	        this->followPush(FOLLOW_comp_term_in_rule238);
            	        comp_term();

            	        this->followPop();
            	        if  (this->hasException())
            	        {
            	            goto ruleruleEx;
            	        }
            	        if (this->hasFailed())
            	        {
            	            return ;
            	        }


            	    }
            	    break;

                }
            }

             this->matchToken(18, &FOLLOW_18_in_rule241);
            if  (this->hasException())
            {
                goto ruleruleEx;
            }
            if (this->hasFailed())
            {
                return ;
            }


            // Prolog.g:48:35: ( ATOM | comp_term )
            {
                int alt6=2;
                switch ( this->LA(1) )
                {
                case ATOM:
                	{
                		switch ( this->LA(2) )
                		{
                		case 16:
                		case 17:
                			{
                				alt6=1;
                			}
                		    break;
                		case 14:
                			{
                				alt6=2;
                			}
                		    break;

                		default:
                		    if (this->get_backtracking()>0)
                		    {
                		        this->set_failedflag( true );
                		        return ;
                		    }

                		    ExceptionBaseType* ex = new ANTLR_Exception< PrologParserImplTraits, NO_VIABLE_ALT_EXCEPTION, StreamType>( this->get_rec(), "" );
                		    ex->set_decisionNum( 6 );
                		    ex->set_state( 1 );


                		    goto ruleruleEx;

                		}

                	}
                    break;

                default:
                    if (this->get_backtracking()>0)
                    {
                        this->set_failedflag( true );
                        return ;
                    }

                    ExceptionBaseType* ex = new ANTLR_Exception< PrologParserImplTraits, NO_VIABLE_ALT_EXCEPTION, StreamType>( this->get_rec(), "" );
                    ex->set_decisionNum( 6 );
                    ex->set_state( 0 );


                    goto ruleruleEx;

                }

                switch (alt6)
                {
            	case 1:
            	    // Prolog.g:48:36: ATOM
            	    {
            	         this->matchToken(ATOM, &FOLLOW_ATOM_in_rule244);
            	        if  (this->hasException())
            	        {
            	            goto ruleruleEx;
            	        }
            	        if (this->hasFailed())
            	        {
            	            return ;
            	        }


            	    }
            	    break;
            	case 2:
            	    // Prolog.g:48:43: comp_term
            	    {
            	        this->followPush(FOLLOW_comp_term_in_rule248);
            	        comp_term();

            	        this->followPop();
            	        if  (this->hasException())
            	        {
            	            goto ruleruleEx;
            	        }
            	        if (this->hasFailed())
            	        {
            	            return ;
            	        }


            	    }
            	    break;

                }
            }

            // Prolog.g:48:54: ( ',' ( ATOM | comp_term ) )*

            for (;;)
            {
                int alt8=2;
                switch ( this->LA(1) )
                {
                case 16:
                	{
                		alt8=1;
                	}
                    break;

                }

                switch (alt8)
                {
            	case 1:
            	    // Prolog.g:48:55: ',' ( ATOM | comp_term )
            	    {
            	         this->matchToken(16, &FOLLOW_16_in_rule252);
            	        if  (this->hasException())
            	        {
            	            goto ruleruleEx;
            	        }
            	        if (this->hasFailed())
            	        {
            	            return ;
            	        }


            	        // Prolog.g:48:59: ( ATOM | comp_term )
            	        {
            	            int alt7=2;
            	            switch ( this->LA(1) )
            	            {
            	            case ATOM:
            	            	{
            	            		switch ( this->LA(2) )
            	            		{
            	            		case 16:
            	            		case 17:
            	            			{
            	            				alt7=1;
            	            			}
            	            		    break;
            	            		case 14:
            	            			{
            	            				alt7=2;
            	            			}
            	            		    break;

            	            		default:
            	            		    if (this->get_backtracking()>0)
            	            		    {
            	            		        this->set_failedflag( true );
            	            		        return ;
            	            		    }

            	            		    ExceptionBaseType* ex = new ANTLR_Exception< PrologParserImplTraits, NO_VIABLE_ALT_EXCEPTION, StreamType>( this->get_rec(), "" );
            	            		    ex->set_decisionNum( 7 );
            	            		    ex->set_state( 1 );


            	            		    goto ruleruleEx;

            	            		}

            	            	}
            	                break;

            	            default:
            	                if (this->get_backtracking()>0)
            	                {
            	                    this->set_failedflag( true );
            	                    return ;
            	                }

            	                ExceptionBaseType* ex = new ANTLR_Exception< PrologParserImplTraits, NO_VIABLE_ALT_EXCEPTION, StreamType>( this->get_rec(), "" );
            	                ex->set_decisionNum( 7 );
            	                ex->set_state( 0 );


            	                goto ruleruleEx;

            	            }

            	            switch (alt7)
            	            {
            	        	case 1:
            	        	    // Prolog.g:48:60: ATOM
            	        	    {
            	        	         this->matchToken(ATOM, &FOLLOW_ATOM_in_rule255);
            	        	        if  (this->hasException())
            	        	        {
            	        	            goto ruleruleEx;
            	        	        }
            	        	        if (this->hasFailed())
            	        	        {
            	        	            return ;
            	        	        }


            	        	    }
            	        	    break;
            	        	case 2:
            	        	    // Prolog.g:48:67: comp_term
            	        	    {
            	        	        this->followPush(FOLLOW_comp_term_in_rule259);
            	        	        comp_term();

            	        	        this->followPop();
            	        	        if  (this->hasException())
            	        	        {
            	        	            goto ruleruleEx;
            	        	        }
            	        	        if (this->hasFailed())
            	        	        {
            	        	            return ;
            	        	        }


            	        	    }
            	        	    break;

            	            }
            	        }

            	    }
            	    break;

            	default:
            	    goto loop8;	/* break out of the loop */
            	    break;
                }
            }
            loop8: ; /* Jump out to here if this rule does not match */


             this->matchToken(17, &FOLLOW_17_in_rule264);
            if  (this->hasException())
            {
                goto ruleruleEx;
            }
            if (this->hasFailed())
            {
                return ;
            }


            if ( this->get_backtracking()==0 )
            {
                std::cout << "matched a rule!" << std::endl;
            }


        }

    }
    // This is where rules clean up and exit
    //
    goto ruleruleEx; /* Prevent compiler warnings */
    ruleruleEx: ;


    	if (this->hasException())
        {
            this->preporterror();
            this->precover();
        }
    return ;
}
/* $ANTLR end rule */

/**
 * $ANTLR start query
 * Prolog.g:51:1: query : ( ATOM | comp_term ) ( ',' ( ATOM | comp_term ) )* '.' ;
 */
void
PrologParser::query()
{
        PrologParserImplTraits::RuleReturnValueType _antlr_rule_exit(this);
      

    /* Initialize rule variables
     */


 
    {
        // Prolog.g:51:9: ( ( ATOM | comp_term ) ( ',' ( ATOM | comp_term ) )* '.' )
        // Prolog.g:51:13: ( ATOM | comp_term ) ( ',' ( ATOM | comp_term ) )* '.'
        {
            // Prolog.g:51:13: ( ATOM | comp_term )
            {
                int alt9=2;
                switch ( this->LA(1) )
                {
                case ATOM:
                	{
                		switch ( this->LA(2) )
                		{
                		case 16:
                		case 17:
                			{
                				alt9=1;
                			}
                		    break;
                		case 14:
                			{
                				alt9=2;
                			}
                		    break;

                		default:
                		    if (this->get_backtracking()>0)
                		    {
                		        this->set_failedflag( true );
                		        return ;
                		    }

                		    ExceptionBaseType* ex = new ANTLR_Exception< PrologParserImplTraits, NO_VIABLE_ALT_EXCEPTION, StreamType>( this->get_rec(), "" );
                		    ex->set_decisionNum( 9 );
                		    ex->set_state( 1 );


                		    goto rulequeryEx;

                		}

                	}
                    break;

                default:
                    if (this->get_backtracking()>0)
                    {
                        this->set_failedflag( true );
                        return ;
                    }

                    ExceptionBaseType* ex = new ANTLR_Exception< PrologParserImplTraits, NO_VIABLE_ALT_EXCEPTION, StreamType>( this->get_rec(), "" );
                    ex->set_decisionNum( 9 );
                    ex->set_state( 0 );


                    goto rulequeryEx;

                }

                switch (alt9)
                {
            	case 1:
            	    // Prolog.g:51:14: ATOM
            	    {
            	         this->matchToken(ATOM, &FOLLOW_ATOM_in_query288);
            	        if  (this->hasException())
            	        {
            	            goto rulequeryEx;
            	        }
            	        if (this->hasFailed())
            	        {
            	            return ;
            	        }


            	    }
            	    break;
            	case 2:
            	    // Prolog.g:51:21: comp_term
            	    {
            	        this->followPush(FOLLOW_comp_term_in_query292);
            	        comp_term();

            	        this->followPop();
            	        if  (this->hasException())
            	        {
            	            goto rulequeryEx;
            	        }
            	        if (this->hasFailed())
            	        {
            	            return ;
            	        }


            	    }
            	    break;

                }
            }

            // Prolog.g:51:32: ( ',' ( ATOM | comp_term ) )*

            for (;;)
            {
                int alt11=2;
                switch ( this->LA(1) )
                {
                case 16:
                	{
                		alt11=1;
                	}
                    break;

                }

                switch (alt11)
                {
            	case 1:
            	    // Prolog.g:51:33: ',' ( ATOM | comp_term )
            	    {
            	         this->matchToken(16, &FOLLOW_16_in_query296);
            	        if  (this->hasException())
            	        {
            	            goto rulequeryEx;
            	        }
            	        if (this->hasFailed())
            	        {
            	            return ;
            	        }


            	        // Prolog.g:51:37: ( ATOM | comp_term )
            	        {
            	            int alt10=2;
            	            switch ( this->LA(1) )
            	            {
            	            case ATOM:
            	            	{
            	            		switch ( this->LA(2) )
            	            		{
            	            		case 16:
            	            		case 17:
            	            			{
            	            				alt10=1;
            	            			}
            	            		    break;
            	            		case 14:
            	            			{
            	            				alt10=2;
            	            			}
            	            		    break;

            	            		default:
            	            		    if (this->get_backtracking()>0)
            	            		    {
            	            		        this->set_failedflag( true );
            	            		        return ;
            	            		    }

            	            		    ExceptionBaseType* ex = new ANTLR_Exception< PrologParserImplTraits, NO_VIABLE_ALT_EXCEPTION, StreamType>( this->get_rec(), "" );
            	            		    ex->set_decisionNum( 10 );
            	            		    ex->set_state( 1 );


            	            		    goto rulequeryEx;

            	            		}

            	            	}
            	                break;

            	            default:
            	                if (this->get_backtracking()>0)
            	                {
            	                    this->set_failedflag( true );
            	                    return ;
            	                }

            	                ExceptionBaseType* ex = new ANTLR_Exception< PrologParserImplTraits, NO_VIABLE_ALT_EXCEPTION, StreamType>( this->get_rec(), "" );
            	                ex->set_decisionNum( 10 );
            	                ex->set_state( 0 );


            	                goto rulequeryEx;

            	            }

            	            switch (alt10)
            	            {
            	        	case 1:
            	        	    // Prolog.g:51:38: ATOM
            	        	    {
            	        	         this->matchToken(ATOM, &FOLLOW_ATOM_in_query299);
            	        	        if  (this->hasException())
            	        	        {
            	        	            goto rulequeryEx;
            	        	        }
            	        	        if (this->hasFailed())
            	        	        {
            	        	            return ;
            	        	        }


            	        	    }
            	        	    break;
            	        	case 2:
            	        	    // Prolog.g:51:45: comp_term
            	        	    {
            	        	        this->followPush(FOLLOW_comp_term_in_query303);
            	        	        comp_term();

            	        	        this->followPop();
            	        	        if  (this->hasException())
            	        	        {
            	        	            goto rulequeryEx;
            	        	        }
            	        	        if (this->hasFailed())
            	        	        {
            	        	            return ;
            	        	        }


            	        	    }
            	        	    break;

            	            }
            	        }

            	    }
            	    break;

            	default:
            	    goto loop11;	/* break out of the loop */
            	    break;
                }
            }
            loop11: ; /* Jump out to here if this rule does not match */


             this->matchToken(17, &FOLLOW_17_in_query308);
            if  (this->hasException())
            {
                goto rulequeryEx;
            }
            if (this->hasFailed())
            {
                return ;
            }


            if ( this->get_backtracking()==0 )
            {
                std::cout << "matched a query!" << std::endl;
            }


        }

    }
    // This is where rules clean up and exit
    //
    goto rulequeryEx; /* Prevent compiler warnings */
    rulequeryEx: ;


    	if (this->hasException())
        {
            this->preporterror();
            this->precover();
        }
    return ;
}
/* $ANTLR end query */

// $ANTLR start synpred1_Prolog
void PrologParser::msynpred1_Prolog_fragment(  )
{
    // Prolog.g:31:12: ( fact )
    // Prolog.g:31:12: fact
    {
        this->followPush(FOLLOW_fact_in_synpred1_Prolog86);
        fact();

        this->followPop();
        if  (this->hasException())
        {
            goto rulesynpred1_PrologEx;
        }
        if (this->hasFailed())
        {
            return ;
        }


    }

// This is where rules clean up and exit
//
goto rulesynpred1_PrologEx; /* Prevent compiler warnings */
rulesynpred1_PrologEx: ;

}
// $ANTLR end synpred1_Prolog

// $ANTLR start synpred2_Prolog
void PrologParser::msynpred2_Prolog_fragment(  )
{
    // Prolog.g:31:19: ( rule )
    // Prolog.g:31:19: rule
    {
        this->followPush(FOLLOW_rule_in_synpred2_Prolog90);
        rule();

        this->followPop();
        if  (this->hasException())
        {
            goto rulesynpred2_PrologEx;
        }
        if (this->hasFailed())
        {
            return ;
        }


    }

// This is where rules clean up and exit
//
goto rulesynpred2_PrologEx; /* Prevent compiler warnings */
rulesynpred2_PrologEx: ;

}
// $ANTLR end synpred2_Prolog

// $ANTLR start synpred3_Prolog
void PrologParser::msynpred3_Prolog_fragment(  )
{
    // Prolog.g:31:26: ( query )
    // Prolog.g:31:26: query
    {
        this->followPush(FOLLOW_query_in_synpred3_Prolog94);
        query();

        this->followPop();
        if  (this->hasException())
        {
            goto rulesynpred3_PrologEx;
        }
        if (this->hasFailed())
        {
            return ;
        }


    }

// This is where rules clean up and exit
//
goto rulesynpred3_PrologEx; /* Prevent compiler warnings */
rulesynpred3_PrologEx: ;

}
// $ANTLR end synpred3_Prolog
/* End of parsing rules
 * ==============================================
 */

/* ==============================================
 * Syntactic predicates
 */
bool PrologParser::msynpred( antlr3::ClassForwarder< synpred2_Prolog >  )
{
    ANTLR_MARKER   start;
    bool  success;

    this->inc_backtracking();
    start	= this->mark();
    this->msynpred2_Prolog_fragment();	    // can never throw exception
    success	= !( this->get_failedflag() );
    this->rewind(start);
    this->dec_backtracking();
    this->set_failedflag(false);
    return success;
}

bool PrologParser::msynpred( antlr3::ClassForwarder< synpred3_Prolog >  )
{
    ANTLR_MARKER   start;
    bool  success;

    this->inc_backtracking();
    start	= this->mark();
    this->msynpred3_Prolog_fragment();	    // can never throw exception
    success	= !( this->get_failedflag() );
    this->rewind(start);
    this->dec_backtracking();
    this->set_failedflag(false);
    return success;
}

bool PrologParser::msynpred( antlr3::ClassForwarder< synpred1_Prolog >  )
{
    ANTLR_MARKER   start;
    bool  success;

    this->inc_backtracking();
    start	= this->mark();
    this->msynpred1_Prolog_fragment();	    // can never throw exception
    success	= !( this->get_failedflag() );
    this->rewind(start);
    this->dec_backtracking();
    this->set_failedflag(false);
    return success;
}

/* End of syntactic predicates
 * ==============================================
 */

	}


/* End of code
 * =============================================================================
 */
